name: Update Cryptohack Info
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Fetch Cryptohack Info
        run: |
          USER="nguyenvh"
          curl -s "https://cryptohack.org/api/user/$USER/" > cryptohack_info.json

          # Format JSON data and prepare the markdown content for the README
          USERNAME=$(jq -r '.username' cryptohack_info.json)
          LEVEL=$(jq '.level' cryptohack_info.json)
          SCORE=$(jq '.score' cryptohack_info.json)
          RANK=$(jq '.rank' cryptohack_info.json)
          SOLVED_COUNT=$(jq '.solved_challenges | length' cryptohack_info.json)
          JOINED=$(jq -r '.joined' cryptohack_info.json)

          # Create the Cryptohack stats block in Markdown format
          echo "## Cryptohack Stats" > cryptohack_info.md
          echo "" >> cryptohack_info.md
          echo "**Username**: [$USERNAME](https://cryptohack.org/user/nguyenvh/)" >> cryptohack_info.md
          echo "- **Level**: $LEVEL" >> cryptohack_info.md
          echo "- **Score**: $SCORE" >> cryptohack_info.md
          echo "- **Rank**: $RANK" >> cryptohack_info.md
          echo "- **Solved Challenges**: $SOLVED_COUNT" >> cryptohack_info.md
          echo "- **Joined**: $JOINED" >> cryptohack_info.md

          echo "[![Readme Card](https://github-readme-stats.vercel.app/api/pin/?username=hocnguyen12&repo=cryptohack&theme=apprentice)](https://github.com/hocnguyen12/cryptohack)"

          # Insert the formatted stats into README.md
          sed -i '/### Cryptohack Stats/,$d' README.md # Remove old stats section
          cat cryptohack_info.md >> README.md        # Append new stats
      - name: Commit changes
        run: |
          git config user.name "hocnguyen12"
          git config user.email "paul.nguyen56545@gmail.com"
          git add README.md
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update Cryptohack info" || exit 0
          fi
          git pull --rebase origin main
          git push
