name: Update Cryptohack Info
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Fetch Cryptohack Info
        run: |
          USER="nguyenvh"
          curl -s "https://cryptohack.org/api/user/$USER/" > cryptohack_info.json

          # Format JSON data and prepare the markdown content for the README
          SCORE=$(jq '.score' cryptohack_info.json)
          RANK=$(jq '.rank' cryptohack_info.json)
          SOLVED_COUNT=$(jq '.solved_challenges | length' cryptohack_info.json)

          # Create the Cryptohack stats block in Markdown format
          echo "## Cryptohack Stats" > cryptohack_info.md
          echo "" >> cryptohack_info.md
          echo "- **Score**: $SCORE" >> cryptohack_info.md
          echo "- **Rank**: $RANK" >> cryptohack_info.md
          echo "- **Solved Challenges**: $SOLVED_COUNT" >> cryptohack_info.md

          # Insert the formatted stats into README.md
          sed -i '/## Cryptohack Stats/,$d' README.md # Remove old stats section
          cat cryptohack_info.md >> README.md        # Append new stats
      - name: Commit changes
        run: |
          git config user.name "hocnguyen12"
          git config user.email "paul.nguyen56545@gmail.com"
          git add README.md
          git commit -m "Update Cryptohack info" || exit 0
          git push
